"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, BatteryCharging, Check, FileText, Home, MapPin, ShieldCheck, Sun } from "lucide-react";
import type { SolarProposal, SolarProposalInput } from "@/lib/solar-proposal";

type FormState = SolarProposalInput & { consentMarketing: boolean };
type Result = { reference: string; proposal: SolarProposal; email: string; pdfUrl: string };

const initialState: FormState = {
  postcode: "", address: "", propertyType: "", ownership: "", roofType: "", roofCovering: "", shading: "", orientation: "",
  consumptionMethod: "profile", householdProfile: "average", futureLoads: [], batteryPreference: "unsure", objective: "reduce_bills",
  firstName: "", lastName: "", email: "", phone: "", preferredContactMethod: "email", preferredContactTime: "any", consentTransactional: false, consentMarketing: false
};

const optionGroups = {
  propertyType: [["detached", "Detached house"], ["semi", "Semi-detached house"], ["terraced", "Terraced house"], ["bungalow", "Bungalow"], ["flat", "Flat or apartment"]],
  ownership: [["yes", "Yes, I own it"], ["no", "No"], ["purchasing", "I am purchasing it"], ["landlord", "I am a landlord or property manager"]],
  roofType: [["pitched", "Pitched roof"], ["flat", "Flat roof"], ["combination", "Combination"], ["ground", "Ground-mounted system"], ["unsure", "I am unsure"]],
  roofCovering: [["tile", "Tile"], ["slate", "Slate"], ["metal", "Metal"], ["membrane", "Flat roof membrane"], ["other", "Other / unsure"]],
  shading: [["minimal", "No or very little shading"], ["some", "Some shading"], ["significant", "Significant shading"], ["unsure", "I am unsure"]],
  orientation: [["south", "South"], ["south_east", "South-east"], ["south_west", "South-west"], ["east", "East"], ["west", "West"], ["multiple", "Multiple directions"], ["unsure", "I am unsure"]],
  batteryPreference: [["self_consumption", "Maximise self-consumption"], ["independence", "Greater energy independence"], ["off_peak", "Charge from a cheaper off-peak tariff"], ["unsure", "Recommend the best option"], ["none", "No battery required"]],
  objective: [["reduce_bills", "Reduce electricity bills"], ["price_protection", "Protect against rising prices"], ["surplus", "Store surplus solar electricity"], ["ev", "Prepare for an electric vehicle"], ["independence", "Increase energy independence"]]
} as const;

const futureOptions = [["ev", "Electric vehicle"], ["heat_pump", "Heat pump"], ["electric_heating", "Electric heating"], ["air_conditioning", "Air conditioning"], ["hot_tub", "Hot tub"], ["extension", "Home extension"], ["home_office", "Working from home"], ["additional_occupants", "Additional occupants"]] as const;

export function SolarProposalFunnel() {
  const [step, setStep] = useState(0);
  const [form, setForm] = useState<FormState>(initialState);
  const [result, setResult] = useState<Result | null>(null);
  const [error, setError] = useState("");
  const [sending, setSending] = useState(false);

  useEffect(() => {
    const saved = window.sessionStorage.getItem("solar-proposal-form");
    if (saved) setForm({ ...initialState, ...JSON.parse(saved) });
  }, []);

  useEffect(() => window.sessionStorage.setItem("solar-proposal-form", JSON.stringify(form)), [form]);

  const progress = Math.round(((step + 1) / 8) * 100);
  const set = (key: keyof FormState, value: string | number | boolean | string[]) => setForm((current) => ({ ...current, [key]: value }));
  const currentOptions = useMemo(() => optionGroups[step === 1 ? "propertyType" : step === 2 ? "ownership" : step === 3 ? "roofType" : step === 4 ? "roofCovering" : step === 5 ? "shading" : "orientation"], [step]);

  function canContinue() {
    if (step === 0) return Boolean(form.postcode && form.address);
    if (step === 1) return Boolean(form.propertyType && form.ownership);
    if (step === 2) return Boolean(form.roofType && form.roofCovering && form.shading && form.orientation);
    if (step === 3) return form.consumptionMethod === "annual" ? Boolean(form.annualConsumption) : form.consumptionMethod === "monthly" ? Boolean(form.monthlySpend) : Boolean(form.householdProfile);
    if (step === 4) return true;
    if (step === 5) return Boolean(form.batteryPreference && form.objective);
    if (step === 7) return Boolean(form.firstName && form.lastName && form.email && form.phone && form.consentTransactional);
    return true;
  }

  async function submit() {
    setError(""); setSending(true);
    const response = await fetch("/api/solar-proposals", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) });
    const body = await response.json().catch(() => null);
    setSending(false);
    if (!response.ok) { setError(body?.error ?? "We could not create the proposal. Please try again."); return; }
    setResult(body); window.sessionStorage.removeItem("solar-proposal-form");
  }

  if (result) return <Results result={result} />;

  return <main className="min-h-screen bg-navy text-white">
    <section className="mx-auto grid min-h-[32rem] max-w-7xl items-center gap-10 px-5 py-14 sm:px-8 lg:grid-cols-[1.05fr_0.95fr] lg:py-24">
      <div>
        <div className="mb-6 flex flex-wrap gap-2 text-xs font-bold uppercase tracking-[0.18em] text-white/60"><span className="rounded-full border border-white/20 px-3 py-2">Solar Direct</span><span className="rounded-full border border-white/20 px-3 py-2">Free feasibility report</span></div>
        <h1 className="max-w-3xl text-4xl font-bold leading-[1.04] tracking-tight sm:text-6xl">Discover how much you could save with solar.</h1>
        <p className="mt-6 max-w-xl text-base leading-8 text-white/70 sm:text-lg">Receive a personalised solar and battery proposal for your home, including your recommended system size, estimated savings and indicative installed price.</p>
        <button className="mt-8 inline-flex min-h-14 items-center gap-3 rounded-btn bg-accent px-6 text-base font-bold text-white shadow-lg transition hover:bg-accent-hover" onClick={() => document.getElementById("proposal-form")?.scrollIntoView({ behavior: "smooth" })}>Create my free solar proposal <ArrowRight size={18} /></button>
        <div className="mt-6 flex flex-wrap gap-x-5 gap-y-2 text-sm text-white/60"><span>Less than 60 seconds</span><span>Delivered by email</span><span>No obligation</span></div>
      </div>
      <div className="relative mx-auto w-full max-w-md rotate-2 rounded-card bg-[#f4efe5] p-5 text-navy shadow-2xl">
        <div className="absolute -right-3 -top-3 rounded-full bg-accent px-3 py-2 text-xs font-bold text-white">Prepared for your home</div>
        <div className="border-b border-navy/10 pb-5"><p className="text-xs font-bold uppercase tracking-[0.2em] text-accent">Solar Direct</p><p className="mt-12 text-3xl font-bold">Your personalised<br />solar proposal</p><p className="mt-3 text-sm text-navy/60">Indicative system design and savings forecast</p></div>
        <div className="grid grid-cols-2 gap-3 py-5 text-sm"><MockStat label="Solar array" value="6.1 kWp" /><MockStat label="Battery" value="10 kWh" /><MockStat label="Annual saving" value="£1,142" /><MockStat label="Payback" value="7.8 years" /></div>
        <div className="rounded-xl bg-navy p-4 text-sm text-white"><p className="font-bold">A clear next step</p><p className="mt-1 text-white/60">Book your complimentary remote survey when you are ready.</p></div>
      </div>
    </section>
    <section id="proposal-form" className="bg-[#f4efe5] px-5 py-12 text-navy sm:px-8 sm:py-20"><div className="mx-auto max-w-3xl"><div className="mb-8 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-accent">Personalised solar proposal</p><p className="mt-2 text-sm text-navy/55">Step {step + 1} of 8</p></div><div className="w-32 rounded-full bg-navy/10"><div className="h-2 rounded-full bg-accent transition-all" style={{ width: `${progress}%` }} /></div></div><div className="rounded-card bg-white p-5 shadow-soft sm:p-10">{renderStep(step, form, set, currentOptions, futureOptions)}{error && <p className="mt-5 rounded-lg bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p>}<div className="mt-8 flex items-center justify-between gap-3 border-t border-navy/10 pt-6"><button className="inline-flex min-h-12 items-center gap-2 rounded-btn px-4 font-bold text-navy/60 hover:bg-navy/5 disabled:invisible" onClick={() => setStep((current) => Math.max(0, current - 1))} disabled={step === 0}><ArrowLeft size={17} /> Back</button>{step < 7 ? <button className="button-primary min-h-12" onClick={() => canContinue() ? setStep((current) => current + 1) : setError("Please complete this step to continue.")}>Continue <ArrowRight size={17} /></button> : <button className="button-primary min-h-12" onClick={submit} disabled={sending}>{sending ? "Creating your proposal..." : "Generate my proposal"} <ArrowRight size={17} /></button>}</div></div></div></section>
    <section className="bg-white px-5 py-12 text-navy sm:px-8 sm:py-16"><div className="mx-auto grid max-w-5xl gap-5 sm:grid-cols-3"><Trust icon={<ShieldCheck />} title="No obligation" text="Your estimate is free and you choose what happens next." /><Trust icon={<FileText />} title="Useful on its own" text="Get a clear preliminary design and savings forecast." /><Trust icon={<Home />} title="Remote first" text="Start with a remote survey - no home visit required." /></div></section>
  </main>;
}

function renderStep(step: number, form: FormState, set: (key: keyof FormState, value: string | number | boolean | string[]) => void, currentOptions: readonly (readonly [string, string])[] | undefined, futureOptions: readonly (readonly [string, string])[]) {
  if (step === 0) return <Question icon={<MapPin />} title="Where is the property?" text="We use your postcode to make the estimate relevant to your area. You can enter the full address manually." ><div className="grid gap-4 sm:grid-cols-2"><label>Postcode<input value={form.postcode} onChange={(e) => set("postcode", e.target.value)} placeholder="IM4 6EE" autoComplete="postal-code" /></label><label>Property address<input value={form.address} onChange={(e) => set("address", e.target.value)} placeholder="House number and street" autoComplete="street-address" /></label></div></Question>;
  if (step === 3) return <Question icon={<Sun />} title="How much electricity do you use?" text="An approximate figure is enough. You can use an annual kWh figure, monthly bill or household profile."><div className="grid gap-3 sm:grid-cols-3">{[["annual", "Annual kWh"], ["monthly", "Monthly bill"], ["profile", "Household profile"]].map(([value, label]) => <Choice key={value} active={form.consumptionMethod === value} onClick={() => set("consumptionMethod", value)} label={label} />)}</div>{form.consumptionMethod === "annual" && <label className="mt-5 block">Annual electricity use (kWh)<input type="number" inputMode="numeric" value={form.annualConsumption ?? ""} onChange={(e) => set("annualConsumption", Number(e.target.value))} placeholder="e.g. 4,000" /></label>}{form.consumptionMethod === "monthly" && <label className="mt-5 block">Average monthly electricity bill (£)<input type="number" inputMode="decimal" value={form.monthlySpend ?? ""} onChange={(e) => set("monthlySpend", Number(e.target.value))} placeholder="e.g. 180" /></label>}{form.consumptionMethod === "profile" && <div className="mt-5 grid gap-3 sm:grid-cols-2">{[["low", "1-2 people, low use"], ["average", "2-3 people, average use"], ["above_average", "3-4 people, above average"], ["high", "4+ people, high use"], ["very_high", "High-use property"]].map(([value, label]) => <Choice key={value} active={form.householdProfile === value} onClick={() => set("householdProfile", value)} label={label} />)}</div>}</Question>;
  if (step === 4) return <Question icon={<Sun />} title="What may your future energy use look like?" text="Select anything you are planning. We will include an editable allowance in the estimate."><div className="grid gap-3 sm:grid-cols-2">{futureOptions.map(([value, label]) => <Choice key={value} active={form.futureLoads.includes(value)} onClick={() => set("futureLoads", form.futureLoads.includes(value) ? form.futureLoads.filter((item) => item !== value) : [...form.futureLoads, value])} label={label} multi />)}</div><p className="mt-4 text-sm text-navy/50">Nothing planned? Continue without selecting anything.</p></Question>;
  if (step === 5) return <Question icon={<BatteryCharging />} title="What should your battery do for you?" text="This helps us choose a sensible battery size and explain the recommendation."><p className="mb-3 text-sm font-bold">Battery preference</p><div className="grid gap-3 sm:grid-cols-2">{optionGroups.batteryPreference.map(([value, label]) => <Choice key={value} active={form.batteryPreference === value} onClick={() => set("batteryPreference", value)} label={label} />)}</div><p className="mb-3 mt-7 text-sm font-bold">What matters most?</p><div className="grid gap-3 sm:grid-cols-2">{optionGroups.objective.map(([value, label]) => <Choice key={value} active={form.objective === value} onClick={() => set("objective", value)} label={label} />)}</div></Question>;
  if (step === 6) { return <Question icon={<FileText />} title="Your preliminary recommendation is ready" text="Based on your answers, we can now prepare the detailed price, savings forecast and PDF proposal. Enter your details on the next step to unlock it."><div className="grid gap-3 sm:grid-cols-3"><PreviewCard label="Solar array" value="4.5-6.5 kWp" /><PreviewCard label="Battery" value={form.batteryPreference === "none" ? "Solar only" : "5-10 kWh"} /><PreviewCard label="Generation" value="Personalised" /></div><p className="mt-6 rounded-xl bg-[#f4efe5] p-4 text-sm leading-6 text-navy/65">This is an indicative assessment, not a final quotation. The final design is confirmed after a remote technical survey.</p></Question>; }
  if (step === 7) return <Question icon={<ShieldCheck />} title="Where should we send your proposal?" text="Your full personalised PDF will be sent by email after you submit these details."><div className="grid gap-4 sm:grid-cols-2"><label>First name<input value={form.firstName} onChange={(e) => set("firstName", e.target.value)} autoComplete="given-name" /></label><label>Last name<input value={form.lastName} onChange={(e) => set("lastName", e.target.value)} autoComplete="family-name" /></label><label>Email address<input type="email" value={form.email} onChange={(e) => set("email", e.target.value)} autoComplete="email" /></label><label>Mobile telephone<input type="tel" value={form.phone} onChange={(e) => set("phone", e.target.value)} autoComplete="tel" /></label></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label>Preferred contact method<select value={form.preferredContactMethod} onChange={(e) => set("preferredContactMethod", e.target.value)}><option value="email">Email</option><option value="telephone">Telephone</option><option value="whatsapp">WhatsApp</option></select></label><label>Best time to contact<select value={form.preferredContactTime} onChange={(e) => set("preferredContactTime", e.target.value)}><option value="any">Any time</option><option value="morning">Morning</option><option value="afternoon">Afternoon</option><option value="evening">Evening</option></select></label></div><label className="mt-6 flex grid-cols-none grid-flow-col items-start justify-start gap-3 text-sm font-medium"><input className="mt-1 size-4 w-auto" type="checkbox" checked={form.consentTransactional} onChange={(e) => set("consentTransactional", e.target.checked)} />I agree to receive my proposal and be contacted by Solar Direct about this quotation.</label><label className="mt-3 flex grid-cols-none grid-flow-col items-start justify-start gap-3 text-sm font-medium text-navy/65"><input className="mt-1 size-4 w-auto" type="checkbox" checked={form.consentMarketing} onChange={(e) => set("consentMarketing", e.target.checked)} />Send me occasional renewable energy advice and offers.</label><p className="mt-4 text-xs leading-5 text-navy/50">By continuing, you agree to our <a className="underline" href="/privacy">privacy policy</a>. Your transactional consent is required to receive the proposal.</p></Question>;
  if (step === 2) return <Question icon={<Sun />} title="Tell us about the roof" text="Choose the closest answers - the remote survey verifies the final details."><p className="mb-3 text-sm font-bold">Roof type</p><div className="grid gap-3 sm:grid-cols-2">{optionGroups.roofType.map(([value, label]) => <Choice key={value} active={form.roofType === value} onClick={() => set("roofType", value)} label={label} />)}</div><p className="mb-3 mt-7 text-sm font-bold">Roof covering</p><div className="grid gap-3 sm:grid-cols-2">{optionGroups.roofCovering.map(([value, label]) => <Choice key={value} active={form.roofCovering === value} onClick={() => set("roofCovering", value)} label={label} />)}</div><p className="mb-3 mt-7 text-sm font-bold">Significant shading?</p><div className="grid gap-3 sm:grid-cols-2">{optionGroups.shading.map(([value, label]) => <Choice key={value} active={form.shading === value} onClick={() => set("shading", value)} label={label} />)}</div><p className="mb-3 mt-7 text-sm font-bold">Main roof direction</p><div className="grid gap-3 sm:grid-cols-2">{optionGroups.orientation.map(([value, label]) => <Choice key={value} active={form.orientation === value} onClick={() => set("orientation", value)} label={label} />)}</div></Question>;
  const key = step === 1 ? "propertyType" : "orientation";
  return <Question icon={<Home />} title="What type of property is this?" text="This helps us frame the preliminary design."><div className="grid gap-3 sm:grid-cols-2">{currentOptions?.map(([value, label]) => <Choice key={value} active={form[key as keyof FormState] === value} onClick={() => set(key as keyof FormState, value)} label={label} />)}</div><div className="mt-7 border-t border-navy/10 pt-7"><p className="mb-3 text-sm font-bold">Do you own the property?</p><div className="grid gap-3 sm:grid-cols-2">{optionGroups.ownership.map(([value, label]) => <Choice key={value} active={form.ownership === value} onClick={() => set("ownership", value)} label={label} />)}</div></div></Question>;
}

function Results({ result }: { result: Result }) { const { proposal } = result; return <main className="min-h-screen bg-[#f4efe5] px-5 py-14 text-navy sm:px-8 sm:py-24"><div className="mx-auto max-w-5xl"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.18em] text-accent">Proposal {result.reference}</p><h1 className="mt-4 text-4xl font-bold tracking-tight sm:text-6xl">Your personalised solar proposal is ready.</h1><p className="mt-5 text-lg leading-8 text-navy/65">We have prepared your preliminary system recommendation. A copy has been requested for <strong>{maskEmail(result.email)}</strong>.</p><a className="mt-6 inline-flex items-center gap-2 font-bold text-accent underline" href={result.pdfUrl} target="_blank" rel="noreferrer">View your proposal PDF <ArrowRight size={17} /></a></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><PreviewCard label="Solar array" value={`${proposal.solarCapacityKwp} kWp`} /><PreviewCard label="Solar panels" value={`${proposal.panelCount} x ${proposal.panelWattage} W`} /><PreviewCard label="Battery" value={proposal.batteryCapacityKwh ? `${proposal.batteryCapacityKwh} kWh` : "Not included"} /><PreviewCard label="Indicative price" value={`£${proposal.priceRange.min.toLocaleString()}-${proposal.priceRange.max.toLocaleString()}`} /></div><div className="mt-5 grid gap-5 lg:grid-cols-[1fr_0.7fr]"><div className="rounded-card bg-white p-6 shadow-soft sm:p-8"><h2 className="text-2xl font-bold">The headline numbers</h2><div className="mt-6 grid gap-5 sm:grid-cols-3"><MockStat label="Annual generation" value={`${proposal.annualGenerationKwh.toLocaleString()} kWh`} /><MockStat label="First-year saving" value={`£${proposal.firstYearSaving.toLocaleString()}`} /><MockStat label="Indicative payback" value={`${proposal.paybackYears} years`} /></div><p className="mt-8 border-t border-navy/10 pt-5 text-sm leading-6 text-navy/60">{proposal.assumptions.join(" ")}</p></div><div className="rounded-card bg-navy p-6 text-white shadow-soft sm:p-8"><BatteryCharging size={30} className="text-accent" /><h2 className="mt-5 text-2xl font-bold">Book your free remote survey</h2><p className="mt-3 text-sm leading-6 text-white/65">Confirm roof suitability, refine the system design and receive a fixed quotation.</p><a className="mt-7 inline-flex min-h-12 items-center gap-2 rounded-btn bg-accent px-5 font-bold text-white hover:bg-accent-hover" href="mailto:info@therenewabledirectory.co.uk?subject=Book my remote solar survey">Request my survey <ArrowRight size={17} /></a></div></div><p className="mt-8 text-xs leading-5 text-navy/50">This is an initial estimate based on the information supplied. Your final system specification and fixed quotation will be confirmed following a technical assessment. Estimated savings are not guaranteed.</p></div></main>; }

function Question({ icon, title, text, children }: { icon: React.ReactNode; title: string; text: string; children: React.ReactNode }) { return <div><div className="mb-8 flex gap-4"><div className="flex size-12 shrink-0 items-center justify-center rounded-xl bg-accent-light text-accent">{icon}</div><div><h2 className="text-2xl font-bold sm:text-3xl">{title}</h2><p className="mt-2 max-w-xl text-sm leading-6 text-navy/60">{text}</p></div></div>{children}</div>; }
function Choice({ label, active, onClick, multi = false }: { label: string; active: boolean; onClick: () => void; multi?: boolean }) { return <button type="button" onClick={onClick} className={`flex min-h-14 items-center justify-between gap-3 rounded-xl border p-4 text-left text-sm font-bold transition ${active ? "border-accent bg-accent-light text-accent-active" : "border-navy/10 bg-white text-navy hover:border-accent/50"}`}><span>{label}</span><span className={`flex size-5 items-center justify-center rounded-${multi ? "md" : "full"} border ${active ? "border-accent bg-accent text-white" : "border-navy/20"}`}>{active && <Check size={13} />}</span></button>; }
function PreviewCard({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-navy/10 bg-white p-4"><p className="text-xs font-bold uppercase tracking-[0.12em] text-navy/45">{label}</p><p className="mt-2 text-xl font-bold">{value}</p></div>; }
function MockStat({ label, value }: { label: string; value: string }) { return <div><p className="text-xs uppercase tracking-[0.12em] text-navy/45">{label}</p><p className="mt-1 text-xl font-bold">{value}</p></div>; }
function Trust({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="flex gap-4"><div className="text-accent">{icon}</div><div><p className="font-bold">{title}</p><p className="mt-1 text-sm leading-6 text-navy/55">{text}</p></div></div>; }
function maskEmail(email: string) { const [name, domain] = email.split("@"); return `${name.slice(0, 2)}***@${domain}`; }
