import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, Award, BadgeCheck, BatteryCharging, BriefcaseBusiness, Check, ChevronRight, CircleDollarSign, Clock3, FileCheck2, Gauge, Globe2, HeartHandshake, House, MapPin, MessageCircle, Phone, Search, ShieldCheck, Sparkles, Star, Sun, Thermometer, Users, Wrench, Zap } from "lucide-react";
import { FAQ, Gallery, MobileActions, QuoteForm } from "@/components/showcase-profile-client";
import { SHOWCASE_PROFILES, showcaseTiers, type ShowcaseTier } from "@/data/showcase-profiles";

export function generateStaticParams() { return showcaseTiers.map((tier) => ({ tier })); }

export async function generateMetadata({ params }: { params: { tier: string } }): Promise<Metadata> {
  const profile = SHOWCASE_PROFILES[params.tier as ShowcaseTier];
  return { title: profile ? `${profile.name} | ${profile.label} demo` : "Installer profile showcase", description: profile?.description };
}

const trustItems = ["MCS Certified", "RECC Member", "NICEIC Approved", "TrustMark Registered", "Fully Insured", "£10m Public Liability", "Finance Available", "10 Year Workmanship", "25 Year Panel Warranty"];
const accreditations = ["MCS", "RECC", "TrustMark", "NICEIC", "NAPIT", "HIES", "IBA", "Octopus Trusted", "Tesla Powerwall", "Sunsynk", "Fox ESS", "GivEnergy", "SolarEdge", "Enphase", "Sigenergy", "Duracell Energy"];
const products = [[Sun, "Solar panels", "Generate clean electricity from your roof."], [BatteryCharging, "Battery storage", "Keep more of your own energy."], [Thermometer, "Heat pumps", "Comfortable, efficient low-carbon heating."], [Zap, "EV charging", "Charge your car at home for less."], [Gauge, "Smart inverters", "Make every kilowatt work harder."], [House, "Commercial solar", "Lower operating costs for your business."]];
const services = ["Solar PV", "Battery Storage", "Heat Pumps", "EV Chargers", "Commercial Solar", "Maintenance", "Bird Protection", "Solar Cleaning", "Electrical Upgrades", "Roof Repairs", "Energy Monitoring", "Smart Home Integration"];
const manufacturers = ["Tesla", "Sigenergy", "Sunsynk", "Fox", "SolarEdge", "Enphase", "Duracell", "GivEnergy", "JA Solar", "Aiko", "LONGi", "Jinko", "Canadian Solar"];
const areas = ["Chester", "Wirral", "Liverpool", "Wrexham", "Conwy", "Llandudno", "Rhyl", "Bangor", "North Wales", "Cheshire", "Merseyside", "West Lancashire"];

function Stars({ rating = "4.9" }: { rating?: string }) { return <span className="stars" aria-label={`${rating} out of 5 stars`}>★★★★★</span>; }
function SectionTitle({ eyebrow, title, copy }: { eyebrow: string; title: string; copy?: string }) { return <div className="section-title"><span className="kicker">{eyebrow}</span><h2>{title}</h2>{copy && <p>{copy}</p>}</div>; }

export default function ShowcaseProfilePage({ params }: { params: { tier: string } }) {
  const profile = SHOWCASE_PROFILES[params.tier as ShowcaseTier];
  if (!profile) notFound();
  const isPremium = profile.tier !== "free";
  return <main className={`showcase-page tier-${profile.tier}`}>
    <div className="demo-bar"><span>SALES SHOWCASE</span><span>Demonstration profile · Not a real installer</span><Link href="/showcase">Compare all packages <ArrowRight size={14} /></Link></div>
    <nav className="showcase-nav"><Link href="/" className="brand-lockup"><span className="brand-mark"><Sun size={19} /></span><span>The Renewable <b>Directory</b></span></Link><div className="nav-links"><a href="#about">About</a><a href="#services">Services</a><a href="#reviews">Reviews</a><a href="#projects">Projects</a></div><a href="#quote" className="nav-cta">Request a quote <ArrowRight size={15} /></a></nav>

    <section className="showcase-hero">
      <div className="hero-copy"><span className="kicker light">{profile.label} · Cheshire and North Wales</span><h1>Trusted local<br /><em>renewable</em> energy specialists.</h1><p>{profile.description}</p><div className="hero-rating"><Stars rating={profile.rating} /><b>{profile.rating}</b><span>{profile.reviews} homeowner reviews</span></div><div className="hero-actions"><a href="#quote" className="green-button">Request a quote <ArrowRight size={17} /></a><a href={`tel:${profile.phone.replaceAll(" ", "")}`} className="outline-button"><Phone size={16} /> Call now</a><a href="https://wa.me/441244567890" className="outline-button hide-mobile"><MessageCircle size={16} /> WhatsApp</a></div><div className="hero-contact"><MapPin size={15} /> Serving homeowners across {profile.territory}</div></div>
      <div className="hero-visual"><img src={profile.hero} alt="Solar panels on a modern home" /><div className="hero-stamp"><span><Stars /></span><b>{profile.rating}</b><small>Rated by homeowners</small></div><div className="hero-caption"><span>01</span><span>Solar · Storage · Heating · EV</span></div></div>
    </section>
    <div className="trust-bar"><div className="trust-score"><Stars rating={profile.rating} /><b>{profile.rating} <small>Average rating</small></b><span>{profile.reviews} reviews</span></div>{(profile.tier === "free" ? ["Local engineers", "Free quotation", "10 Year Workmanship", "25 Year Panel Warranty"] : trustItems).map((item) => <span key={item}><Check size={14} /> {item}</span>)}</div>

    {profile.priority && <div className="response-banner"><Sparkles size={18} /><b>Priority response guarantee</b><span>Average response within {profile.response.toLowerCase()} — your enquiry is first in the queue.</span><a href="#quote">Get priority advice <ArrowRight size={15} /></a></div>}

    <section id="about" className="section about-section"><div className="about-grid"><div><SectionTitle eyebrow="The company behind the work" title={`A better way to power your home.`} /><p className="about-copy">{profile.about}</p><div className="signature"><div className="signature-mark">{profile.name.split(" ").map((word) => word[0]).join("").slice(0, 2)}</div><div><b>{profile.name}</b><span>Renewable energy, thoughtfully delivered.</span></div></div></div><aside className="snapshot-card"><div className="snapshot-top"><span className="kicker">At a glance</span><span className="verified-dot"><BadgeCheck size={16} /> {profile.verified ? "Verified business" : "Local listing"}</span></div>{[[BriefcaseBusiness, "Established", profile.established], [Users, "Engineers", profile.engineers], [Sun, "Projects completed", `${profile.projects}+`], [Clock3, "Response time", profile.response], [Wrench, "Typical installation", profile.installTime], [ShieldCheck, "Warranty", "10 / 25 years"]].map(([Icon, label, value]) => <div className="snapshot-row" key={label as string}><Icon size={17} /><span>{label as string}</span><b>{value as string}</b></div>)}</aside></div></section>

    {isPremium && <section className="section proof-section"><SectionTitle eyebrow="Visible proof" title="Credentials homeowners can trust." copy="Every badge is a shortcut to confidence. Each one can be clicked to learn exactly what it means." /><div className="accreditation-grid">{accreditations.map((name, i) => <div className="accreditation" key={name}><span className="acc-icon">{i < 4 ? <ShieldCheck size={22} /> : <Award size={22} />}</span><b>{name}</b><small>{i < 4 ? "Accredited standard" : "Approved partner"}</small></div>)}</div></section>}

    <section id="services" className="section services-section"><SectionTitle eyebrow="What we install" title="One expert team for your whole energy system." /><div className="product-grid">{products.map(([Icon, name, copy]) => <div className="product-card" key={name as string}><span className="product-icon"><Icon size={24} /></span><h3>{name as string}</h3><p>{copy as string}</p><a href="#quote">Explore service <ArrowRight size={15} /></a></div>)}</div><div className="service-list"><span className="kicker">Also available</span>{services.map((service) => <span key={service}><Check size={14} />{service}</span>)}</div></section>

    <section className="section dark-section"><div className="why-grid"><div><SectionTitle eyebrow="The difference" title="Made to feel easy from day one." copy="A premium profile gives homeowners more reasons to choose you—and fewer reasons to keep searching." /></div><div className="why-list">{["MCS certified & fully insured", "Local engineers, no subcontractors", "Premium equipment, carefully specified", "Dedicated project manager", "Finance options made clear", "Aftercare included as standard", "No hidden costs or hard sell", "25 year product warranties"].map((item, i) => <div key={item}><span>0{i + 1}</span><b>{item}</b><Check size={16} /></div>)}</div></div></section>

    {profile.tier !== "free" && <section className="section gallery-section" id="projects"><SectionTitle eyebrow="Work we are proud of" title="See the difference in the details." copy={`${profile.projects}+ projects completed, from smart family homes to ambitious commercial systems.`} /><Gallery profile={profile} /></section>}
    {profile.tier === "free" && <section className="section starter-project"><div className="starter-project-image"><img src={profile.hero} alt="Renewable installation" /></div><div><span className="kicker">Featured project</span><h2>A considered start to a cleaner future.</h2><p>A snapshot of the project quality and local expertise homeowners can expect from this listing.</p><div className="project-meta"><span><b>4.8 kWp</b> Solar PV</span><span><b>10 kWh</b> Battery</span><span><b>2 days</b> Duration</span></div><a href="#quote" className="text-link">View case study <ArrowRight size={15} /></a></div></section>}

    {profile.tier === "featured" && <section className="section analytics-section"><div><span className="kicker">Performance snapshot</span><h2>A profile that works as hard as you do.</h2><p>Featured positioning turns attention into measurable homeowner enquiries.</p></div><div className="analytics-card"><div><small>Profile views</small><b>2,841</b><span className="up">↑ 28% this month</span></div><div className="bars"><i style={{height:"42%"}} /><i style={{height:"66%"}} /><i style={{height:"53%"}} /><i style={{height:"84%"}} /><i style={{height:"72%"}} /><i style={{height:"100%"}} /></div><span className="chart-label">Last 6 months</span></div></section>}

    {profile.priority && <section className="section priority-tools"><SectionTitle eyebrow="Priority partner advantage" title="Your profile becomes a lead engine." copy="Priority Lead Partners are built to own attention in their territory and turn every click into a trackable opportunity." /><div className="tool-grid">{[[Gauge,"Live lead dashboard","See every enquiry, response and outcome in one place."],[Search,"Monthly SEO report","Know where your profile is winning local search."],[FileCheck2,"Lead history","A clear record of every homeowner conversation."],[HeartHandshake,"Dedicated account manager","A partner to help your listing perform at its best."]].map(([Icon, title, copy]) => <div key={title as string} className="tool-card"><Icon size={23} /><h3>{title as string}</h3><p>{copy as string}</p><span>Included in Priority <Check size={14} /></span></div>)}</div></section>}

    <section className="section map-section"><div className="map-card"><div className="map-art"><div className="map-grid-lines" /><div className="map-pin pin-a"><MapPin /></div><div className="map-pin pin-b"><MapPin /></div><div className="map-pin pin-c"><MapPin /></div><div className="map-radius" /><span className="map-label">{profile.map}</span></div><div className="map-copy"><span className="kicker">Local by design</span><h2>Expert help, close to home.</h2><p>Serving {profile.territory} with local engineers who understand the homes, weather and energy needs of the region.</p><div className="areas"><div className="area-search"><Search size={16} /><input placeholder="Search service areas" /></div><div className="area-chips">{areas.map((area) => <span key={area}>{area}</span>)}</div></div></div></div></section>

    <section id="reviews" className="section reviews-section"><div className="reviews-header"><SectionTitle eyebrow="Homeowner reviews" title="Rated highly. Recommended freely." /><div className="rating-card"><b>{profile.rating}</b><Stars rating={profile.rating} /><span>Based on {profile.reviews} verified reviews</span></div></div><div className="review-grid">{[["Sarah & Tom", "Chester", "From first survey to final handover, everything was explained clearly. The team were tidy, thoughtful and a pleasure to have around."],["James W.", "Wrexham", "Our energy bills are already lower and the battery has changed the way we use the house. Brilliant workmanship and communication."],["Helen R.", "Wirral", "A genuinely professional experience. The system looks fantastic and we always knew what was happening next."]].map(([name, location, quote], i) => <article className="review-card" key={name}><div className="review-head"><span className="avatar">{name[0]}</span><div><b>{name}</b><small><MapPin size={12} /> {location} · Verified homeowner</small></div><Stars /></div><p>“{quote}”</p><div className="review-footer"><span>Solar PV · Battery storage</span><span>Installation {12 + i}/06/24</span></div></article>)}</div></section>

    <section className="section manufacturers"><SectionTitle eyebrow="Equipment we trust" title="Premium products. Properly installed." /><div className="manufacturer-row">{manufacturers.map((m) => <span key={m}>{m}</span>)}</div><div className="finance-grid">{[[CircleDollarSign,"0% finance","Spread the cost on selected systems."],[Clock3,"Flexible payments","Options built around your budget."],[ShieldCheck,"Clear guarantees","Confidence long after installation day."]].map(([Icon, title, copy]) => <div key={title as string}><Icon size={21} /><b>{title as string}</b><p>{copy as string}</p></div>)}</div><small className="finance-note">Finance subject to status, terms and conditions.</small></section>

    <section className="section cases-section"><SectionTitle eyebrow="Proof in practice" title="Real homes. Real outcomes." /><div className="case-grid">{Array.from({length: Math.min(profile.caseStudies, 3)}).map((_, i) => <article key={i} className="case-card"><div className="case-image"><img src={profile.images[i % profile.images.length]} alt="Renewable energy project" /><span>Case study 0{i + 1}</span></div><div className="case-body"><span className="kicker">{i === 0 ? "Chester" : i === 1 ? "Wrexham" : "Wirral"}</span><h3>{i === 0 ? "A smarter, more independent family home" : i === 1 ? "Solar designed around real life" : "Comfort and control, all year round"}</h3><p>Solar PV, battery storage and smart energy controls designed for the way this home lives.</p><div className="case-stats"><span><b>{i === 0 ? "£1,240" : "£980"}</b> est. annual saving</span><span><b>1–2 days</b> installation</span></div></div></article>)}</div></section>

    <section className="section faq-section"><SectionTitle eyebrow="Good to know" title="Questions, answered clearly." /><FAQ /></section>
    <section id="quote" className="quote-section"><div className="quote-intro"><span className="kicker light">Let’s make a plan</span><h2>Ready to reduce your energy bills?</h2><p>Request a free quotation from {profile.name} today. No obligation, no pressure.</p><div className="quote-direct"><a href={`tel:${profile.phone.replaceAll(" ", "")}`}><Phone size={17} /> {profile.phone}</a><a href="https://wa.me/441244567890"><MessageCircle size={17} /> WhatsApp us</a></div></div><QuoteForm profile={profile} /></section>
    <footer className="showcase-footer"><Link href="/" className="brand-lockup"><span className="brand-mark"><Sun size={17} /></span><span>The Renewable <b>Directory</b></span></Link><span>Demonstration profile · © 2026 The Renewable Directory</span><Link href="/showcase">View package comparison <ChevronRight size={14} /></Link></footer>
    <MobileActions profile={profile} />
    <a href="https://wa.me/441244567890" className="floating-whatsapp" aria-label="WhatsApp"><MessageCircle size={23} /></a>
  </main>;
}
